### ISSUE TITLE
REVIEW Week7

### ISSUE THREAD

**Issue by tienyulin** [KeroKnows/s-killer#7]
1. Please merge all the previous code into master branch before week8's assignments.
@nlpersimon

**Comment by nlpersimon** [comment]
> 1. Please merge all the previous code into master branch before week8's assignments.
>    @nlpersimon

Hi,
All the previous code have already been merged into the master branch, and other branches were not deleted.

**Comment by tienyulin** [comment]
Oops, It seems like I posted on the wrong team, sorry for that. But I haven't reviewed your code. So don't close this issue.

**Comment by nlpersimon** [comment]
Copy that, thank you!

**Comment by tienyulin** [comment]
1. Recommend to put different entities to different files.
https://github.com/KeroKnows/s-killer/blob/master/app/models/entities/job.rb

2. SearchApi and DetailApi can put into Api as methods, it meaningless to make them a class. https://github.com/KeroKnows/s-killer/blob/master/app/models/gateways/reed_api.rb

3. Recommend to put PartialJobMapper and JobMapper to different files. 
https://github.com/KeroKnows/s-killer/blob/master/app/models/mappers/reed_mappers/job_mapper.rb

4. `before block` use to do some job before your test like load some data or initialize something, so it’s not proper to put your test in `before block`. https://github.com/KeroKnows/s-killer/blob/master/spec/reed_spec.rb#L57

5. Test failed, I rename `secrets_example.yml` to `secrets.yml` to run your tests.

**Comment by nlpersimon** [comment]
Thank you for the advice!

We have [addressed items 1. ~ 3.](https://github.com/KeroKnows/s-killer/pull/9) , and will address the item 4. tomorrow.

**Comment by nlpersimon** [comment]
We have [addressed the item 4.](https://github.com/KeroKnows/s-killer/pull/10),
and all the modifications were merged into the `develop` branch.

The tests are able to pass with the sample secrets file now.

**Comment by tienyulin** [comment]
Great! Keep working on this week's assignments and remember to make a PR from develop to master. Good luck!
